#!/usr/bin/env python3

from __future__ import annotations

import sys
import urllib.request
from pathlib import Path

import yaml


UPSTREAM_URL = (
    "https://raw.githubusercontent.com/"
    "mihomo-party-org/override-hub/main/yaml/"
    "ACL4SSR_Online_Full_WithIcon.yaml"
)

ROOT = Path(__file__).resolve().parent.parent
PATCH_FILE = ROOT / "patch" / "custom-rules.yaml"
OUTPUT_FILE = ROOT / "dist" / "ACL4SSR_Online_Full_WithIcon_Custom.yaml"


def load_yaml_file(path: Path):
    with path.open("r", encoding="utf-8") as f:
        return yaml.safe_load(f) or {}


def download_yaml(url: str):
    request = urllib.request.Request(
        url,
        headers={
            "User-Agent": "vpsrules-ACL4SSR-builder/1.0"
        },
    )

    with urllib.request.urlopen(request, timeout=30) as response:
        text = response.read().decode("utf-8")

    data = yaml.safe_load(text)

    if not isinstance(data, dict):
        raise ValueError("Upstream YAML root must be a mapping.")

    return data


def merge_proxy_groups(upstream: dict, patch: dict):
    custom_groups = patch.get("proxy-groups", []) or []

    if not isinstance(custom_groups, list):
        raise ValueError("'proxy-groups' in patch must be a list.")

    existing_groups = upstream.setdefault("proxy-groups", [])

    if not isinstance(existing_groups, list):
        raise ValueError("'proxy-groups' in upstream must be a list.")

    existing_names = {
        item.get("name")
        for item in existing_groups
        if isinstance(item, dict) and item.get("name")
    }

    for group in custom_groups:
        if not isinstance(group, dict):
            raise ValueError("Each custom proxy-group must be a mapping.")

        name = group.get("name")

        if not name:
            raise ValueError("Each custom proxy-group must have a name.")

        if name in existing_names:
            raise ValueError(
                f"Custom proxy-group '{name}' conflicts with upstream."
            )

        existing_groups.append(group)
        existing_names.add(name)


def merge_rule_providers(upstream: dict, patch: dict):
    custom_providers = patch.get("rule-providers", {}) or {}

    if not isinstance(custom_providers, dict):
        raise ValueError("'rule-providers' in patch must be a mapping.")

    existing_providers = upstream.setdefault("rule-providers", {})

    if not isinstance(existing_providers, dict):
        raise ValueError("'rule-providers' in upstream must be a mapping.")

    for name, provider in custom_providers.items():
        if name in existing_providers:
            raise ValueError(
                f"Custom rule-provider '{name}' conflicts with upstream."
            )

        existing_providers[name] = provider


def merge_rules(upstream: dict, patch: dict):
    prepend_rules = patch.get("prepend-rules", []) or []
    append_rules = patch.get("append-rules", []) or []

    if not isinstance(prepend_rules, list):
        raise ValueError("'prepend-rules' must be a list.")

    if not isinstance(append_rules, list):
        raise ValueError("'append-rules' must be a list.")

    upstream_rules = upstream.get("rules", []) or []

    if not isinstance(upstream_rules, list):
        raise ValueError("'rules' in upstream must be a list.")

    upstream["rules"] = prepend_rules + upstream_rules + append_rules


def main():
    print(f"Downloading upstream:\n{UPSTREAM_URL}")

    upstream = download_yaml(UPSTREAM_URL)

    print(f"Loading patch:\n{PATCH_FILE}")

    patch = load_yaml_file(PATCH_FILE)

    merge_proxy_groups(upstream, patch)
    merge_rule_providers(upstream, patch)
    merge_rules(upstream, patch)

    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)

    header = """\
# ============================================================
# AUTO-GENERATED FILE — DO NOT EDIT DIRECTLY
#
# Source:
# ACL4SSR_Online_Full_WithIcon.yaml
#
# Custom additions:
# patch/custom-rules.yaml
#
# Generated by:
# scripts/merge.py
# ============================================================

"""

    rendered = yaml.safe_dump(
        upstream,
        allow_unicode=True,
        sort_keys=False,
        default_flow_style=False,
        width=4096,
    )

    OUTPUT_FILE.write_text(
        header + rendered,
        encoding="utf-8",
    )

    print(f"Generated:\n{OUTPUT_FILE}")


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        sys.exit(1)
